### ISSUE TITLE
Support for U+201C, U+201D quotes

### ISSUE THREAD

**Issue by cilim** [JakariaBlaine/str_sanitizer#7]
Really cool gem!

It would be nice if it supports removing the double quotation marks that get created in files such as .xlsx, .ods, .docx etc...

This is what I've tried:

```ruby
hello = '“String with them funny quotation marks”'
StrSanitizer.has_any_quote?(hello)
nil
```
The thing is that the `"` is different from the opening `“` and closing quotation mark `”`.

**Comment by Abu-Zakaria** [comment]
thanks a lot for opening the issue, mate.... :)

you can also fork this repo and try to add that function to your forked repo and create a pull request..... ;)

[_sorry for the late reply, I was on a vacation_]

**Comment by Abu-Zakaria** [comment]
the issue is fixed... thanks to @bjacquet
